# Generated by Django 5.1.5 on 2025-01-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del dispositivo')),
                ('fabricante', models.CharField(max_length=50, unique=True, verbose_name='Nombre del fabricante')),
                ('fecha_lanzamiento', models.DateField(verbose_name='fecha de lanzamiento')),
                ('precio', models.IntegerField(verbose_name='Precio ')),
                ('sistemaOperativo', models.CharField(max_length=100, unique=True, verbose_name='Sistema Operativo del dispositivo')),
                ('disponibilidad', models.BooleanField(verbose_name='disponibilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
                'ordering': ['nombre'],
            },
        ),
    ]
